### PR TITLE
add logos for the gnuradio-ci user

### PR DESCRIPTION
**Pull request by noc0lour**
merge the buildbot nut into the GNU Radio logo as profile picture
for the CI user

### CODE REVIEW

**Comment by noc0lour** [comment]
The buildbot logo is apparently GPL licensed, do I need to throw in a GPL copyright notice in there as well?

**Comment by mbr0wn** [comment]
Yes, please don't give the armchair lawyers no reason to call us out here. I'm also not sure what license the combined logo becomes. Is the GNU Radio logo now also GPL?

**Comment by rgetz** [comment]
This project's readme.md

```
The logo is owned by The GNU Radio Foundation and is licensed under a
Creative Commons Attribution-NoDerives (CC BY-ND 2.0) license:
http://creativecommons.org/licenses/by-nd/2.0/
```

which is described as:
```
NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.
```

**Comment by mbr0wn** [comment]
We can give permission to modify the logo to individuals such as @noc0lour. I'm just going to hit merge here.

**Pull request merged**
